M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2026-09-26T03:31:19+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-26T03:31:19+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.400
%
G90
G05
T1
X97.11Y-153.395
X102.89Y-153.395
T2
X142.0Y-130.9
X142.0Y-138.4
T3
X18.0Y-74.25
X18.0Y-106.75
X18.0Y-145.25
M30
