M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu24.04.1} date 2026-09-24T09:10:30+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-24T09:10:30+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.850
%
G90
G05
T1
X97.11Y-153.395
X102.89Y-153.395
T2
X142.0Y-130.9
X142.0Y-138.4
T3
X61.9Y-50.5
X61.9Y-170.5
X118.9Y-50.5
X118.9Y-170.5
M30
